Repository planetarium/libplanet-explorer, pull requests merged in 2019-08, with the labels that each got.

#31 Add options of blocks, offset and limit
  Libplanet.Explorer/GraphTypes/BlocksQuery.cs
Labels: enhancement

#32 Refine GraphQL APIs
  Libplanet.Explorer/ExplorerStartup.cs
  Libplanet.Explorer/GraphTypes/BlockType.cs
  Libplanet.Explorer/GraphTypes/BlocksQuery.cs
  Libplanet.Explorer/GraphTypes/TransactionType.cs
Labels: enhancement

#36 More comprehensive introduction
  README.md
Labels: enhancement

#39 Richer types
  Libplanet.Explorer/Controllers/ExplorerController.cs
  Libplanet.Explorer/GraphTypes/ActionArgumentType.cs
  Libplanet.Explorer/GraphTypes/ActionType.cs
  Libplanet.Explorer/GraphTypes/AddressType.cs
  Libplanet.Explorer/GraphTypes/BlockType.cs
  Libplanet.Explorer/GraphTypes/ByteStringType.cs
  Libplanet.Explorer/GraphTypes/PlainValueKeyValuePairType.cs
  Libplanet.Explorer/GraphTypes/TransactionType.cs
Labels: enhancement

#41 Optimize blocks query
  Libplanet.Explorer/GraphTypes/BlocksQuery.cs
Labels: bug, enhancement

#49 Search block by blockHash in O(1)
  Libplanet.Explorer/GraphTypes/BlocksQuery.cs
Labels: good first issue

#55 Add transactions query by signer or involved address
  Libplanet.Explorer/GraphTypes/AddressType.cs
  Libplanet.Explorer/GraphTypes/BlocksQuery.cs
Labels: enhancement, good first issue

#57 Replace Mono.Options with CommandLineParser
  Libplanet.Explorer.Executable/Libplanet.Explorer.Executable.csproj
  Libplanet.Explorer.Executable/Options.cs
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Explorer.Executable/StoreRegistry.cs
Labels: enhancement

#58 Online mode
  Libplanet.Explorer.Executable/Libplanet.Explorer.Executable.csproj
  Libplanet.Explorer.Executable/Options.cs
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Explorer/Controllers/ExplorerController.cs
  Libplanet.Explorer/ExplorerStartup.cs
  Libplanet.Explorer/Interfaces/IBlockChainContext.cs
  Libplanet.Explorer/Interfaces/IBlockchainStore.cs
  Libplanet.Explorer/Libplanet.Explorer.csproj
Labels: enhancement
